sudo: required
services:
  - docker

before_install:
  - docker build -t vonpappen/docker-react -f Dockerfile.dev . 

scripts:
  - docker run -e CI=true vonpappen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-934116018902"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY